default: &default
  adapter:  postgresql
  encoding: utf8
  username: <%= ENV['DB_USERNAME'] %>
  password:
  pool: 5
  host:  <%= ENV['DB_HOST'] || 'localhost' %>
  timeout: 5000

development:
  <<: *default
  database: url_shortening

test:
  <<: *default
  database: url_shortening_test
