# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19aeb080dd05b2ef98974981d807fa8f18fbd3ae692d60775959fe52ee54b33b93273dc75dae0bea8ece810d9fd98388aeb1b18045767f52420c27f57f10e61f
  bitly_url_shortener:
    base_path: https://api-ssl.bitly.com/v3/shorten
    key: dd67b22401c0ed17b7fb92961321149c0da4a497

test:
  secret_key_base: 1b664ce2a079072da0340f75cb45c697d0502620d52471853b23f8c42e293ad8954736b934959d62788600d4d788ed4c69cab10c48209c81d1b2560bc48de797

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
